-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 21, 2016 at 03:40 PM
-- Server version: 5.5.52-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `users`
--

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(832, '', '', 'aCarter@gmail.com', 'U5A92I7G!8', 'Cairistiona', 'Turnerasd', '2016-08-26', 'Pollicetur certe.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sedulo, inquam, faciam. Duo Reges: constructio interrete. Tecum optime, deinde etiam cum mediocri amico. Tum mihi Piso: Quid ergo? \n\n', '4868 Wandle Street', 'Halifax', 'B5B T0S', 'Maine', 'Jordan', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(833, '', '', 'rRebelo@gmail.com', '6CDC7P0K!8', 'Mariellen', 'Kelsey', '2012-03-26', 'Quid autem habent admirationis, cum prope accesseris?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quantum Aristoxeni ingenium consumptum videmus in musicis? Ea possunt paria non esse. Quae cum dixisset, finem ille. \n\n', '3603 Emmet Road', 'Oakleigh', 'WF GQ', 'Indiana', 'Montserrat', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(834, '', '', 'aBickers@gmail.com', '2Z56VKK7!8', 'Mira', 'Starck', '2004-10-23', 'Non modo carum sibi quemque, verum etiam vehementer carum esse?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. At hoc in eo M. Quo tandem modo? Num quid tale Democritus? Cur post Tarentum ad Archytam? Duo Reges: constructio interrete. \n\n', '8139 Pitman Street', 'York', 'C6Y G0T', 'Indiana', 'Benin', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(835, '', '', 'aRohloff@gmail.com', 'Q2XGBF0Z!8', 'Stacey', 'Pullman', '2007-02-14', 'Aufert enim sensus actionemque tollit omnem.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Restinguet citius, si ardentem acceperit. Ad eos igitur converte te, quaeso. Qui convenit? Tuo vero id quidem, inquam, arbitratu. Duo Reges: constructio interrete. \n\n', '2422 Winston Road', 'Bakersfield', 'L2L U5X', 'Nunavut', 'Korea, Democratic People"S Republic of', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(836, '', '', 'lCumbie@gmail.com', 'E5SCUY8N!8', 'Carina', 'Zobel', '2013-08-28', 'An dolor longissimus quisque miserrimus, voluptatem non optabiliorem diuturnitas facit?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc tu nunc in illo probas. Sedulo, inquam, faciam. Sed nunc, quod agimus; Sed haec omittamus; \n\n', '2006 Brentwood Drive', 'Cambridge', 'MZ X7H', 'Missouri', 'Myanmar', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(837, '', '', 'rHottle@gmail.com', 'FEM0553S!8', 'Cecilla', 'Hundt', '2000-07-18', 'Hos contra singulos dici est melius.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Perge porro; Sit enim idem caecus, debilis. Quid enim possumus hoc agere divinius? Age, inquies, ista parva sunt. \n\n', '4911 Fairmont Avenue', 'Spokane', 'H9A U4H', 'Michigan', 'Northern Mariana Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(838, '', '', 'lKrumm@gmail.com', 'MG6SAV12!8', 'Addy', 'Seal', '2003-07-05', 'Ita relinquet duas, de quibus etiam atque etiam consideret.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nihilo magis. Laboro autem non sine causa; Equidem e Cn. Ne discipulum abducam, times. \n\n', '8869 Winchester Drive', 'Woodville', 'S3I T2L', 'West Virginia', 'Albania', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(840, '', '', 'eBourquin@gmail.com', 'WV1HE8L2!8', 'Di', 'Sager', '2015-04-15', 'Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Frater et T. Quorum altera prosunt, nocent altera. \n\n', '6115 Templeton Parkway', 'Portland', 'E2Q B1Y', 'Georgia', 'Antigua and Barbuda', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(841, '', '', 'hHottle@gmail.com', 'G1OZLQIM!8', 'Bernelle', 'Murphy', '2003-08-10', 'An vero, inquit, quisquam potest probare, quod perceptfum, quod.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem e Cn. Duo Reges: constructio interrete. Deinde dolorem quem maximum? \n\n', '729 Clemont Street', 'Lewisburg', 'H8C L3I', 'Kentucky', 'Israel', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(842, '', '', 'dBacker@gmail.com', 'Y9DJ2OPQ!8', 'Lisabeth', 'Correa', '2004-05-28', 'Nam ante Aristippus, et ille melius.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Quis enim redargueret? Collige omnia, quae soletis: Praesidium amicorum. Quo modo? Bonum incolumis acies: misera caecitas. Efficiens dici potest. Si longus, levis dictata sunt. \n\n', '7117 Brentwood Drive', 'Newark', 'G5Z Z4W', 'Manitoba', 'Kazakhstan', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(843, '', '', 'eRohloff@gmail.com', 'K1K1TE8W!8', 'Adriana', 'Hottle', '2003-11-24', 'Hoc enim constituto in philosophia constituta sunt omnia.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mehercule pergrata mihi oratio tua. Ut pulsi recurrant? \n\n', '1474 Dunstable Street', 'Dallas', 'K8W F2T', 'New Mexico', 'Netherlands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(844, '', '', 'oCharley@gmail.com', '1ZJC9T54!8', 'Kit', 'Tuck', '2006-06-02', 'Quod non faceret, si in voluptate summum bonum poneret.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quo modo autem philosophus loquitur? Laboro autem non sine causa; Sed quot homines, tot sententiae; Urgent tamen et nihil remittunt. \n\n', '4953 Ceder Avenue', 'Stanford', 'E1L P0I', 'Alberta', 'Congo, The Democratic Republic of the', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(845, '', '', 'nCappel@gmail.com', '80QMQDZF!8', 'Susanne', 'Rebelo', '2002-01-09', 'Quae cum praeponunt, ut sit aliqua rerum selectio, naturam videntur sequi;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sint modo partes vitae beatae. At enim sequor utilitatem. Duo Reges: constructio interrete. \n\n', '5701 Tower Lane', 'Orlando', 'H6V L0J', 'Kansas', 'Cook Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(846, '', '', 'eLuck@gmail.com', '8VG28M8V!8', 'Etty', 'Grieve', '2013-11-17', 'Qui ita affectus, beatum esse numquam probabis;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nonne igitur tibi videntur, inquit, mala? Sed ad illum redeo. Duo Reges: constructio interrete. Nulla erit controversia. \n\n', '2836 Alexander Avenue', 'Dublin', 'QH M1N', 'Rhode Island', 'Hong Kong', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(847, '', '', 'rLenihan@gmail.com', '984CG2CZ!8', 'Natalee', 'Charley', '2008-07-17', 'Quod iam a me expectare noli.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quam si explicavisset, non tam haesitaret. Quo igitur, inquit, modo? Et nemo nimium beatus est; Avaritiamne minuis? \n\n', '1757 Springfield Street', 'Halifax', 'Q2E X8E', 'British Columbia', 'Isle of Man', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(848, '', '', 'dLatshaw@gmail.com', '0FRRZYKW!8', 'Loralyn', 'Drolet', '2004-10-05', 'Quarum ambarum rerum cum medicinam pollicetur, luxuriae licentiam pollicetur.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Vide, quantum, inquam, fallare, Torquate. At enim hic etiam dolore. Cyrenaici quidem non recusant; Id enim natura desiderat. Duo Reges: constructio interrete. Primum quid tu dicis breve? Hic ambiguo ludimur. \n\n', '6999 Seaside Drive', 'Newark', 'W4C A8N', 'Washington', 'Norway', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(849, '', '', 'aLatshaw@gmail.com', '0ZK56RNV!8', 'Gipsy', 'Fennell', '2006-04-11', 'Sit hoc ultimum bonorum, quod nunc a me defenditur;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nihilo magis. Duo Reges: constructio interrete. Quo modo autem philosophus loquitur? Tamen a proposito, inquam, aberramus. \n\n', '6820 Hunter Street', 'Stafford', 'T4M GL', 'Arizona', 'El Salvador', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(850, '', '', 'eDunham@gmail.com', 'V6NV51ZY!8', 'Emera', 'Dampier', '2015-08-10', 'Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Hic nihil fuit, quod quaereremus. Immo videri fortasse. Sed ea mala virtuti magnitudine obruebantur. \n\n', '4460 Mercer Street', 'Youngstown', 'K8Q VK', 'Missouri', 'El Salvador', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(851, '', '', 'aHollis@gmail.com', 'ZZ2HDBGT!8', 'Chere', 'Cappel', '2014-01-20', 'Verum esto: verbum ipsum voluptatis non habet dignitatem, nec nos fortasse intellegimus.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Facete M. Facillimum id quidem est, inquam. \n\n', '1136 Alexander Avenue', 'Hartford', 'B5X I4T', 'Ohio', 'Dominica', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(852, '', '', 'iBacker@gmail.com', '4LSX77AP!8', 'Codie', 'Pullman', '2001-04-22', 'Nihil minus, contraque illa hereditate dives ob eamque rem laetus.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Cur, nisi quod turpis oratio est? Quid ergo attinet gloriose loqui, nisi constanter loquare? Quis Aristidem non mortuum diligit? Quis enim redargueret? Duo Reges: constructio interrete. Confecta res esset. \n\n', '6508 Golden Lane', 'Newark', 'J5S H3N', 'Montana', 'Austria', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(853, '', '', 'oStarck@gmail.com', '6FDOKI7K!8', 'Rora', 'Gamble', '2010-03-26', 'Quicquid enim a sapientia proficiscitur, id continuo debet expletum esse omnibus suis partibus;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc Hieronymus summum bonum esse dixit. Istic sum, inquit. At certe gravius. Negare non possum. Audeo dicere, inquit. Duo Reges: constructio interrete. \n\n', '4881 Mercer Street', 'Greenville', 'M7O MM', 'Kansas', 'Mauritania', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(854, '', '', 'aBourquin@gmail.com', '9FN12T6G!8', 'Gwendolen', 'Cappel', '2001-06-18', 'An haec ab eo non dicuntur?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Neutrum vero, inquit ille. De vacuitate doloris eadem sententia erit. Inde igitur, inquit, ordiendum est. Duo Reges: constructio interrete. \n\n', '3537 Rivington Street', 'Cleveland', '8L E2B', 'Oregon', 'Finland', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(855, '', '', 'sChapman@gmail.com', 'NBMP4XOR!8', 'Adda', 'Kelsey', '2007-11-15', 'Quis suae urbis conservatorem Codrum, quis Erechthei filias non maxime laudat?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nihil opus est exemplis hoc facere longius. Duo Reges: constructio interrete. Explanetur igitur. Tum mihi Piso: Quid ergo? Cur iustitia laudatur? Recte, inquit, intellegis. \n\n', '449 Pearl Street', 'Orlando', 'B6T L7P', 'British Columbia', 'Micronesia, Federated States of', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(856, '', '', 'iConnor@gmail.com', '10QH94RZ!8', 'Dodi', 'Muldoon', '2011-06-03', 'Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quod quidem nobis non saepe contingit. Minime vero istorum quidem, inquit. Duo Reges: constructio interrete. Itaque contra est, ac dicitis; \n\n', '9094 Taylor Street', 'Palmerston', '7N R2Q', 'Wyoming', 'Isle of Man', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(857, '', '', 'lMagby@gmail.com', 'LLW4FIOS!8', 'Claudia', 'Paquette', '2011-11-10', 'Memini vero, inquam;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quid me istud rogas? Comprehensum, quod cognitum non habet? Immo alio genere; Duo Reges: constructio interrete. Minime vero istorum quidem, inquit. Iam in altera philosophiae parte. Quis enim redargueret? \n\n', '607 Wooster Road', 'Richmond', 'Q4Y J6A', 'Northwest Territories', 'Tuvalu', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(858, '', '', 'lBourquin@gmail.com', 'N9G8SKC6!8', 'May', 'Pickering', '2014-12-29', 'Sed tamen intellego quid velit.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Iam enim adesse poterit. Duo Reges: constructio interrete. Sed ego in hoc resisto; An tu me de L. Quo modo autem philosophus loquitur? Quo modo? Traditur, inquit, ab Epicuro ratio neglegendi doloris. Aliter enim explicari, quod quaeritur, non potest. \n\n', '7846 Crockett Street', 'Walkerville', 'F I7L', 'Alberta', 'Faroe Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(859, '', '', 'uHottle@gmail.com', 'J7S8BBV7!8', 'Alethea', 'Garling', '2010-09-05', 'Quae cum dixisset paulumque institisset, Quid est?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Primum Theophrasti, Strato, physicum se voluit; Nos commodius agimus. Nihil illinc huc pervenit. Quis Aristidem non mortuum diligit? \n\n', '2496 Bushey Crescent', 'Redmond', 'G2N I2J', 'New Brunswick', 'Palau', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(860, '', '', 'oDurrett@gmail.com', 'D9KXQXL1!8', 'Karine', 'Bickers', '2003-12-11', 'Si stante, hoc natura videlicet vult, salvam esse se, quod concedimus;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Equidem e Cn. Refert tamen, quo modo. \n\n', '5256 Brook Street', 'Bangor', 'I8M V4U', 'Maine', 'Jersey', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(861, '', '', 'lCastleman@gmail.com', 'BH9S24NZ!8', 'Christie', 'Tuck', '2012-01-16', 'Age, inquies, ista parva sunt.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Eam stabilem appellas. Quod cum dixissent, ille contra. Duo Reges: constructio interrete. \n\n', '17 Hill Street', 'Oxford', 'Q7W I4E', 'South Carolina', 'Virgin Islands, U.S.', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(862, '', '', 'rCarroll@gmail.com', '6ZI9CPX9!8', 'Tara', 'Flinn', '2005-04-04', 'Theophrastus mediocriterne delectat, cum tractat locos ab Aristotele ante tractatos?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quo igitur, inquit, modo? Urgent tamen et nihil remittunt. \n\n', '9993 Stockton Lane', 'Portland', 'L7A B2Y', 'Kansas', 'Nauru', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(863, '', '', 'aRohloff@gmail.com', '9RR2M1QY!8', 'Merrilee', 'Hottle', '2006-12-28', 'Ergo in gubernando nihil, in officio plurimum interest, quo in genere peccetur.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Numquam facies. Quid vero? Sin aliud quid voles, postea. Nemo igitur esse beatus potest. \n\n', '7836 Main Street', 'Toronto', 'I2W Z7L', 'Oregon', 'Sri Lanka', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(864, '', '', 'aSmit@gmail.com', '3C8P0LRS!8', 'Corissa', 'Connor', '2003-12-17', 'Scaevola tribunus plebis ferret ad plebem vellentne de ea re quaeri.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Confecta res esset. An haec ab eo non dicuntur? Duo Reges: constructio interrete. Recte, inquit, intellegis. Ecce aliud simile dissimile. Tria genera bonorum; Cur id non ita fit? Istam voluptatem, inquit, Epicurus ignorat? \n\n', '6796 Appleton Street', 'Dundee', 'Q4 X8K', 'Michigan', 'Tokelau', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(865, '', '', 'aHyder@gmail.com', '2M3DNYBQ!8', 'Dara', 'Mullens', '2003-09-25', 'Hoc mihi cum tuo fratre convenit.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Prave, nequiter, turpiter cenabat; Illi enim inter se dissentiunt. Duo Reges: constructio interrete. \n\n', '2855 Windsor Avenue', 'Canterbury', 'H8Z I9G', 'Nunavut', 'Timor-Leste', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(866, '', '', 'nMagby@gmail.com', 'B6CZTDU2!8', 'Petunia', 'Smit', '2003-08-29', 'Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quid Zeno? Quid, si etiam iucunda memoria est praeteritorum malorum? Haeret in salebra. Sed plane dicit quod intellegit. Duo Reges: constructio interrete. Invidiosum nomen est, infame, suspectum. \n\n', '943 Harrington Crescent', 'Stafford', 'E7I S4G', 'Michigan', 'Iceland', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(867, '', '', 'lSchaefer@gmail.com', 'Q0UJKXL0!8', 'Kristine', 'Rebelo', '2008-05-07', 'Duo Reges: constructio interrete.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Tenent mordicus. Idemne, quod iucunde? At enim sequor utilitatem. \n\n', '7712 Brentwood Drive', 'Christchurch', 'J9S N2O', 'New Hampshire', 'Heard Island and Mcdonald Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(868, '', '', 'dHottle@gmail.com', '1Q301EIM!8', 'Ali', 'Matzen', '2010-08-02', 'Traditur, inquit, ab Epicuro ratio neglegendi doloris.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Pauca mutat vel plura sane; Sed in rebus apertissimis nimium longi sumus. Sedulo, inquam, faciam. Bonum valitudo: miser morbus. Si longus, levis; \n\n', '7541 Springfield Street', 'Norwich', 'UJ XQ', 'Idaho', 'Luxembourg', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(869, '', '', 'eCaffey@gmail.com', 'T7W9IAMM!8', 'Cloe', 'Raymond', '2008-11-10', 'Fortasse id optimum, sed ubi illud: Plus semper voluptatis?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Nulla erit controversia. Quibusnam praeteritis? Moriatur, inquit. \n\n', '2614 Glenn Drive', 'Portland', 'G6H Z7V', 'Oklahoma', 'Sri Lanka', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(870, '', '', 'iPace@gmail.com', 'GP1EY83K!8', 'Kellsie', 'Cappel', '2010-09-14', 'Dulce amarum, leve asperum, prope longe, stare movere, quadratum rotundum.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ad rem redeamus; Sin aliud quid voles, postea. \n\n', '4017 Park Avenue', 'York', 'V1G I0U', 'Georgia', 'Cocos (Keeling) Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(871, '', '', 'iWebster@gmail.com', 'H54RVNNV!8', 'Kettie', 'Higgins', '2006-11-13', 'Minime vero, inquit ille, consentit.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Confecta res esset. Quis hoc dicit? Nihilo magis. Praeclare hoc quidem. Quid ad utilitatem tantae pecuniae? Duo Reges: constructio interrete. Immo videri fortasse. \n\n', '3098 Beechmont Parkway', 'Spokane', 'U1Q Q3F', 'Wisconsin', 'South Georgia and the South Sandwich Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(872, '', '', 'eChapman@gmail.com', 'V86L9WX3!8', 'Maurizia', 'Starck', '2002-07-17', 'Cur deinde Metrodori liberos commendas?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Efficiens dici potest. Itaque his sapiens semper vacabit. Tubulo putas dicere? Duo Reges: constructio interrete. Quo modo? Immo alio genere; Paria sunt igitur. Hoc loco tenere se Triarius non potuit. \n\n', '4310 Elton Way', 'Chicago', 'F0B Z7K', 'British Columbia', 'Trinidad and Tobago', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(873, '', '', 'lWallis@gmail.com', 'G5RE6G68!8', 'Junina', 'Carter', '2004-03-15', 'Quid enim ab antiquis ex eo genere, quod ad disserendum valet, praetermissum est?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. In schola desinis. Facillimum id quidem est, inquam. Si longus, levis. \n\n', '7562 Carter Street', 'Fresno', 'Z9Q W', 'North Dakota', 'Poland', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(874, '', '', 'iTuck@gmail.com', '5TRSQSJI!8', 'Meryl', 'Mullens', '2002-12-26', 'Unum est sine dolore esse, alterum cum voluptate.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quonam modo? Et ille ridens: Video, inquit, quid agas; Duo Reges: constructio interrete. Inde igitur, inquit, ordiendum est. \n\n', '423 Mulholland Drive', 'Kingston', 'P4 HB', 'Montana', 'Spain', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(875, '', '', 'rCadena@gmail.com', 'Y26D2RV9!8', 'Tyne', 'Charley', '2013-04-07', 'Quorum sine causa fieri nihil putandum est.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Minime vero istorum quidem, inquit. Maximus dolor, inquit, brevis est. Confecta res esset. Duo Reges: constructio interrete. Non est igitur summum malum dolor. \n\n', '8361 Baker Street', 'Greenville', 'W1Y 0V', 'Utah', 'Germany', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(876, '', '', 'aBradbury@gmail.com', 'PS784I88!8', 'Melanie', 'Remus', '2016-06-28', 'Nec hoc ille non vidit, sed verborum magnificentia est et gloria delectatus.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Haec para/doca illi, nos admirabilia dicamus. Certe non potest. Hoc simile tandem est? Nescio quo modo praetervolavit oratio. \n\n', '978 Haredale Road', 'Danbury', 'O6D 6V', 'British Columbia', 'Tokelau', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(877, '', '', 'aVerde@gmail.com', 'VCPXV35V!8', 'Flossi', 'Caffey', '2003-03-01', 'Quae diligentissime contra Aristonem dicuntur a Chryippo.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quid ad utilitatem tantae pecuniae? Duo Reges: constructio interrete. Quid Zeno? Simus igitur contenti his. \n\n', '1659 Glenn Drive', 'Norfolk', 'R2Z F2Z', 'Wisconsin', 'Nepal', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(878, '', '', 'aWinter@gmail.com', 'OQVUZ6TP!8', 'Lou', 'Miers', '2016-04-12', 'Illi enim inter se dissentiunt.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Sin aliud quid voles, postea. Ostendit pedes et pectus. Egone quaeris, inquit, quid sentiam? \n\n', '1740 Brentwood Drive', 'Bradford', 'I6R U6D', 'Indiana', 'Belize', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(879, '', '', 'ePace@gmail.com', 'NXH6ZPGM!8', 'Doralynne', 'Friedrich', '2009-02-14', 'Non quam nostram quidem, inquit Pomponius iocans;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ego in hoc resisto; Sed haec omittamus; Murenam te accusante defenderem. Pollicetur certe. Duo Reges: constructio interrete. \n\n', '7204 Main Street', 'Stafford', 'J3W TZ', 'Louisiana', 'Mauritius', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(880, '', '', 'eConnor@gmail.com', '713SOLW9!8', 'Anetta', 'Paschall', '2007-08-15', 'Ut optime, secundum naturam affectum esse possit.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Praeclarae mortes sunt imperatoriae; Duo Reges: constructio interrete. Et quod est munus, quod opus sapientiae? Comprehensum, quod cognitum non habet? Equidem e Cn. \n\n', '695 Coleman Avenue', 'Irvine', 'R7B X7J', 'Hawaii', 'Timor-Leste', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(881, '', '', 'aRikard@gmail.com', 'ZTL27RAV!8', 'Larisa', 'Webster', '2007-11-12', 'Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Non est igitur voluptas bonum. Deprehensus omnem poenam contemnet. Duo Reges: constructio interrete. Bonum integritas corporis: misera debilitas. \n\n', '528 Foster Walk', 'Dallas', 'B1M Z9N', 'Pennsylvania', 'Antigua and Barbuda', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(882, '', '', 'eHundt@gmail.com', '598Y26PH!8', 'Loraine', 'Pleiman', '2001-10-13', 'Haec et tu ita posuisti, et verba vestra sunt.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quis enim redargueret? Tuo vero id quidem, inquam, arbitratu. Cur id non ita fit? Tamen a proposito, inquam, aberramus. \n\n', '8602 Warner Street', 'Auckland', 'D4R 2E', 'Vermont', 'Liberia', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(883, '', '', 'aSager@gmail.com', 'P39H98M8!8', 'Marybelle', 'Zobel', '2014-03-09', 'Non autem hoc: igitur ne illud quidem.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Frater et T. Ecce aliud simile dissimile. Cur post Tarentum ad Archytam? Hunc vos beatum; Non igitur bene. \n\n', '7123 Elm Street', 'Albany', 'L1K L3O', 'Arizona', 'Afghanistan', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(884, '', '', 'oYoung@gmail.com', 'R95NPMBK!8', 'Galina', 'Wallis', '2004-12-13', 'Qui ita affectus, beatum esse numquam probabis;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quippe: habes enim a rhetoribus; Cave putes quicquam esse verius. Que Manilium, ab iisque M. Summum a vobis bonum voluptas dicitur. \n\n', '632 Fairmont Avenue', 'Manchester', 'M2D E4I', 'New Brunswick', 'Antarctica', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(885, '', '', 'uMatzen@gmail.com', 'OGEKZ96H!8', 'Nolie', 'Shelly', '2003-06-22', 'Quis istud possit, inquit, negare?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Vide, quaeso, rectumne sit. Qualem igitur hominem natura inchoavit? Cur, nisi quod turpis oratio est? Duo Reges: constructio interrete. Sed ad bona praeterita redeamus. \n\n', '9616 Hunt Street', 'Sacramento', 'U4G BN', 'Minnesota', 'Turkey', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(886, '', '', 'mConnor@gmail.com', 'AC6PWOZX!8', 'Patience', 'Dunham', '2016-09-28', 'Quae cum dixisset paulumque institisset, Quid est?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Avaritiamne minuis? Quonam modo? \n\n', '5317 Seaside Drive', 'Newcastle', 'W5S N0L', 'Nova Scotia', 'Cocos (Keeling) Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(887, '', '', 'aFlinn@gmail.com', 'YZ0MBW4X!8', 'Astrid', 'Brandt', '2008-12-09', 'Unum nescio, quo modo possit, si luxuriosus sit, finitas cupiditates habere.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quod cum dixissent, ille contra. Nihil illinc huc pervenit. A mene tu? Sed haec omittamus; Duo Reges: constructio interrete. Sit sane ista voluptas. Id mihi magnum videtur. \n\n', '4497 Glenn Drive', 'Exeter', 'V5O O8', 'Virginia', 'Myanmar', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(888, '', '', 'aSeal@gmail.com', 'TY2ZXXC5!8', 'Saundra', 'Drolet', '2011-01-22', 'Facillimum id quidem est, inquam.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Non autem hoc: igitur ne illud quidem. Praeclarae mortes sunt imperatoriae; Sed nimis multa. Minime vero, inquit ille, consentit. Quis istud possit, inquit, negare? At multis se probavit. \n\n', '4186 Fairmont Avenue', 'Rochester', 'T2Z M9N', 'Montana', 'Vanuatu', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(889, '', '', 'mHollis@gmail.com', 'VQS18CFN!8', 'Ardenea', 'test', '2016-09-21', 'Aliter homines, aliter philosophos loqui putas oportere?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Si quae forte-possumus. Ita nemo beato beatior. Summus dolor plures dies manere non potest? Duo Reges: constructio interrete. \n\n', '5966 Longford Crescent', 'Wilmington', 'K2F M2G', 'Ontario', 'Canada', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(890, '', '', 'eLatshaw@gmail.com', 'OB882AEU!8', 'Corilla', 'Porras', '2011-05-08', 'Longum est enim ad omnia respondere, quae a te dicta sunt.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sedulo, inquam, faciam. Idemne, quod iucunde? Occultum facinus esse potuerit, gaudebit; Negare non possum. \n\n', '1853 Harrington Crescent', 'York', 'E7H V9X', 'Quebec', 'South Africa', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(891, '', '', 'aStarck@gmail.com', '6B90GRQB!8', 'Annette', 'Pace', '2011-01-04', 'Cum audissem Antiochum, Brute, ut solebam, cum M.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Tubulo putas dicere? A mene tu? Duo Reges: constructio interrete. Sed plane dicit quod intellegit. Videsne quam sit magna dissensio? Si longus, levis. Honesta oratio, Socratica, Platonis etiam. Quid enim? \n\n', '3611 Ceder Avenue', 'Pheonix', 'X8S T2M', 'Hawaii', 'Afghanistan', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(892, '', '', 'rPettey@gmail.com', '5DE9RGNV!8', 'Ashil', 'Cumbie', '2016-02-22', 'Hos contra singulos dici est melius.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quo modo autem philosophus loquitur? Duo Reges: constructio interrete. Memini me adesse P. Fortemne possumus dicere eundem illum Torquatum? \n\n', '7504 Wooster Road', 'York', 'U0U G3C', 'Louisiana', 'Egypt', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(893, '', '', 'aHollis@gmail.com', 'R0CAZSZ8!8', 'Rozamond', 'Pleiman', '2016-12-05', 'Multa sunt dicta ab antiquis de contemnendis ac despiciendis rebus humanis;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Minime vero, inquit ille, consentit. Tibi hoc incredibile, quod beatissimum. Ergo, inquit, tibi Q. Duo Reges: constructio interrete. Proclivi currit oratio. Beatus sibi videtur esse moriens. Quare conare, quaeso. \n\n', '7719 Sterling Street', 'Tacoma', 'R3V M7R', 'Saskatchewan', 'Cook Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(894, '', '', 'rFriedrich@gmail.com', '7IGM7C7E!8', 'Maryl', 'Rohloff', '2007-10-09', 'Vitiosum est enim in dividendo partem in genere numerare.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Dici enim nihil potest verius. Quorum sine causa fieri nihil putandum est. Itaque contra est, ac dicitis; Sed ea mala virtuti magnitudine obruebantur. \n\n', '5532 Warner Street', 'Danbury', 'U7M S1V', 'Michigan', 'Timor-Leste', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(896, '', '', 'iCarter@gmail.com', '3IYMC3XB!8', 'Adeyasd', 'Nealasd', '2007-02-27', 'Eam tum adesse, cum dolor omnis absit;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Cum audissem Antiochum, Brute, ut solebam, cum M. Frater et T. Duo Reges: constructio interrete. Tu quidem reddes; \n\n', '7875 Robinson Street', 'Bakersfield', 'S0E U7I', 'Newfoundland and Labrador', 'Algeria', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(897, '', '', 'aGrieve@gmail.com', 'CYHN2B8T!8', 'Amalita', 'Schaefer', '2009-01-27', 'Post enim Chrysippum eum non sane est disputatum.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Non laboro, inquit, de nomine. Duo Reges: constructio interrete. \n\n', '6499 Clarendon Street', 'Bristol', 'IZ I9J', 'Maine', 'Eritrea', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(898, '', '', 'iFinn@gmail.com', 'AUF4HCET!8', 'Nance', 'Carroll', '2005-05-14', 'Sed eum qui audiebant, quoad poterant, defendebant sententiam suam.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Ita prorsus, inquam; Quam ob rem tandem, inquit, non satisfacit? Scrupulum, inquam, abeunti; Contineo me ab exemplis. Perge porro; Falli igitur possumus. Duo Reges: constructio interrete. \n\n', '9545 Springfield Street', 'Columbia', 'Q1N Q5R', 'Kentucky', 'Tajikistan', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(899, '', '', 'aVerde@gmail.com', '46HXB76B!8', 'Marjie', 'White', '2014-11-28', 'Res enim se praeclare habebat, et quidem in utraque parte.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Ille incendat? At certe gravius. \n\n', '3837 Tavistock Place', 'Danbury', 'B2Z W6K', 'Newfoundland and Labrador', 'El Salvador', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(900, '', '', 'iZobel@gmail.com', '6E3OKUW3!8', 'Vale', 'Bourne', '2015-12-28', 'Non est ista, inquam, Piso, magna dissensio.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sumenda potius quam expetenda. Haec igitur Epicuri non probo, inquam. Duo Reges: constructio interrete. Sed ego in hoc resisto; \n\n', '9272 Waverton Street', 'Bakersfield', 'P3Z B6E', 'Maine', 'Uganda', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(901, '', '', 'eFriedrich@gmail.com', '141RVDJ1!8', 'Walliw', 'Dampier', '2001-02-15', 'Ea possunt paria non esse.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nemo igitur esse beatus potest. Sint ista Graecorum; Quae cum essent dicta, discessimus. Duo Reges: constructio interrete. \n\n', '6551 Crockett Street', 'Cambridge', 'L5Z H2U', 'Washington', 'Uzbekistan', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(902, '', '', 'oGarling@gmail.com', '5NQNND65!8', 'Prissie', 'Coolidge', '2003-01-22', 'Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Suam denique cuique naturam esse ad vivendum ducem. At eum nihili facit; Memini me adesse P. Frater et T. \n\n', '6324 Ceder Avenue', 'Cleveland', 'S8G Q4', 'Hawaii', 'Swaziland', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(903, '', '', 'hPorras@gmail.com', 'FF2C3X8H!8', 'Yasmin', 'Young', '2002-08-13', 'Hic nihil fuit, quod quaereremus.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Age, inquies, ista parva sunt. Teneo, inquit, finem illi videri nihil dolere. Duo Reges: constructio interrete. Nos vero, inquit ille; \n\n', '7896 Berkeley Street', 'Bradford', 'D9X J5C', 'Ontario', 'Virgin Islands, U.S.', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(904, '', '', 'rPaquette@gmail.com', '1A5N0B95!8', 'Nichole', 'Karst', '2007-03-25', 'Rapior illuc, revocat autem Antiochus, nec est praeterea, quem audiamus.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. De illis, cum volemus. Itaque his sapiens semper vacabit. Quid ad utilitatem tantae pecuniae? Duo Reges: constructio interrete. \n\n', '8653 Haredale Road', 'Beaverton', 'Y5V R5Q', 'Wyoming', 'Dominica', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(905, '', '', 'yCaffey@gmail.com', '4LPG39R2!8', 'Tate', 'Carter', '2011-01-28', 'In schola desinis.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quod quidem nobis non saepe contingit. Sint modo partes vitae beatae. Sint ista Graecorum; \n\n', '9081 Hinton Road', 'Portsmouth', 'Y1M YQ', 'Pennsylvania', 'New Caledonia', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(906, '', '', 'aSeal@gmail.com', 'EX7JIMHV!8', 'Jemima', 'Carter', '2010-04-12', 'Itaque hic ipse iam pridem est reiectus;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Fortemne possumus dicere eundem illum Torquatum? Hunc vos beatum; Duo Reges: constructio interrete. Summus dolor plures dies manere non potest? \n\n', '1947 Banner Street', 'Atlanta', 'O2X M8H', 'Virginia', 'Japan', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(907, '', '', 'oMercer@gmail.com', 'PAG8AMR5!8', 'Klarika', 'Keesee', '2004-08-26', 'Legimus tamen Diogenem, Antipatrum, Mnesarchum, Panaetium, multos alios in primisque familiarem nostrum Posidonium.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quid autem habent admirationis, cum prope accesseris? Velut ego nunc moveor. Duo Reges: constructio interrete. Summum enÃ­m bonum exposuit vacuitatem doloris; Bonum valitudo: miser morbus. Quid Zeno? Nam ante Aristippus, et ille melius. \n\n', '1199 Alexander Avenue', 'Northampton', 'P R8E', 'Colorado', 'Latvia', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(908, '', '', 'aFinn@gmail.com', '7LAE8VLX!8', 'Angil', 'Raymond', '2009-04-19', 'Sapientem locupletat ipsa natura, cuius divitias Epicurus parabiles esse docuit.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Faceres tu quidem, Torquate, haec omnia; Quid Zeno? Proclivi currit oratio. Duo Reges: constructio interrete. Illi enim inter se dissentiunt. Sedulo, inquam, faciam. \n\n', '2162 Coleman Avenue', 'Charleston', 'Q2K T5L', 'Washington', 'Morocco', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(909, '', '', 'aDunham@gmail.com', 'BVABZOQ7!8', 'Cornie', 'Tindel', '2005-01-14', 'Sic, et quidem diligentius saepiusque ista loquemur inter nos agemusque communiter.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Comprehensum, quod cognitum non habet? Duo Reges: constructio interrete. \n\n', '165 Carter Street', 'Chicago', 'R4T F0K', 'Indiana', 'Lesotho', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(910, '', '', 'dGamble@gmail.com', '75HEXBVO!8', 'Inga', 'Hottle', '2005-12-01', 'Videmus igitur ut conquiescere ne infantes quidem possint.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nos commodius agimus. Quid censes in Latino fore? Sed haec omittamus; Duo Reges: constructio interrete. Prave, nequiter, turpiter cenabat; Quid censes in Latino fore? \n\n', '9484 Springfield Street', 'Atlanta', 'K4E N0R', 'Iowa', 'Congo, The Democratic Republic of the', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(911, '', '', 'hMullens@gmail.com', 'RM8KJAKX!8', 'Shelby', 'Miers', '2004-07-02', 'Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quod equidem non reprehendo; De quibus cupio scire quid sentias. Dicimus aliquem hilare vivere; Negat enim summo bono afferre incrementum diem. Sed ego in hoc resisto; Duo Reges: constructio interrete. Illi enim inter se dissentiunt. Sed nimis multa. \n\n', '2811 Harrington Crescent', 'Norfolk', 'Q3O O8O', 'California', 'Saint Vincent and the Grenadines', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(912, '', '', 'iGoudy@gmail.com', 'G0IZEHZM!8', 'Claire', 'Coolidge', '2012-06-13', 'Sed plane dicit quod intellegit.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Praeclare hoc quidem. Non est igitur voluptas bonum. Comprehensum, quod cognitum non habet? Non est igitur voluptas bonum. Sed quot homines, tot sententiae; Duo Reges: constructio interrete. An tu me de L. \n\n', '2442 Warner Street', 'Rochester', 'K7Z J7P', 'Ontario', 'Mongolia', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(913, '', '', 'rRisley@gmail.com', 'NZ4OTZWK!8', 'Cosetta', 'Neal', '2004-12-04', 'Huius ego nunc auctoritatem sequens idem faciam.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. At eum nihili facit; A mene tu? Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Tubulo putas dicere? Cur deinde Metrodori liberos commendas? Sedulo, inquam, faciam. \n\n', '4161 Concord Avenue', 'Woodville', 'W4L T1B', 'Ontario', 'Cayman Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(914, '', '', 'aMilligan@gmail.com', 'H2JAVNTT!8', 'Karita', 'Sprowl', '2001-06-29', 'Aliter enim nosmet ipsos nosse non possumus.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Teneo, inquit, finem illi videri nihil dolere. Haec para/doca illi, nos admirabilia dicamus. Quid iudicant sensus? Duo Reges: constructio interrete. Aliter enim explicari, quod quaeritur, non potest. Nos commodius agimus. \n\n', '5105 Sleepy Lane', 'Woodville', 'C5S A8V', 'Georgia', 'Barbados', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(915, '', '', 'vFriedrich@gmail.com', 'O4TUCOB4!8', 'Janean', 'Neal', '2002-05-27', 'Quid, quod res alia tota est?\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Tu quidem reddes; Suo genere perveniant ad extremum; Quonam, inquit, modo? Id enim natura desiderat. Quare conare, quaeso. Duo Reges: constructio interrete. \n\n', '3377 Harrington Crescent', 'Bangor', 'J2 W0X', 'Oklahoma', 'Kazakhstan', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(916, '', '', 'aFriedrich@gmail.com', 'EGXA64Z5!8', 'Shirlene', 'Bradbury', '2010-01-27', 'Conferam tecum, quam cuique verso rem subicias;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quid ad utilitatem tantae pecuniae? In schola desinis. Paria sunt igitur. Certe, nisi voluptatem tanti aestimaretis. \n\n', '4656 Tower Lane', 'Denver', 'E2L Y0B', 'Vermont', 'Faroe Islands', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(917, '', '', 'eFriedrich@gmail.com', '08A6CHXJ!8', 'Aloisia', 'Durrett', '2008-11-07', 'Septem autem illi non suo, sed populorum suffragio omnium nominati sunt.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Deinde dolorem quem maximum? Dici enim nihil potest verius. Cur post Tarentum ad Archytam? Duo Reges: constructio interrete. Eadem nunc mea adversum te oratio est. Cur haec eadem Democritus? \n\n', '4757 Buckley Street', 'Danbury', 'T3T D1R', 'Arizona', 'Moldova, Republic of', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(918, '', '', 'dMiers@gmail.com', 'Y9IA3BWN!8', 'Tessy', 'Bourne', '2008-08-02', 'Atqui eorum nihil est eius generis, ut sit in fine atque extrerno bonorum.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quid censes in Latino fore? Audeo dicere, inquit. Neutrum vero, inquit ille. Optime, inquam. Vide, quaeso, rectumne sit. Duo Reges: constructio interrete. \n\n', '7843 Hunter Street', 'Bristol', 'S0D Q3E', 'Delaware', 'Kiribati', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(919, '', '', 'aLatshaw@gmail.com', 'YW4P86ML!8', 'Guinevere', 'Matzen', '2001-11-23', 'Ergo hoc quidem apparet, nos ad agendum esse natos.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quis enim redargueret? Atqui reperies, inquit, in hoc quidem pertinacem; \n\n', '1735 Hartswood Road', 'Palmerston', 'N8V S0D', 'Alberta', 'Mauritius', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(920, '', '', 'lSager@gmail.com', 'UV5E3Z39!8', 'Coriss', 'Keesee', '2016-02-02', 'Praeclarae mortes sunt imperatoriae;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Si enim ad populum me vocas, eum. Inde igitur, inquit, ordiendum est. Si longus, levis. Non semper, inquam; Sed haec omittamus; Duo Reges: constructio interrete. \n\n', '2524 Banner Street', 'Lewisburg', 'R1I O3W', 'Nevada', 'Maldives', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(921, '', '', 'eMilling@gmail.com', 'OIKEH1RK!8', 'Emelda', 'Bickers', '2001-05-21', 'Laboro autem non sine causa;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Eademne, quae restincta siti? Tubulo putas dicere? \n\n', '9437 Hartswood Road', 'Rochester', 'NX 0K', 'Minnesota', 'Holy See (Vatican City State)', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(922, '', '', 'eBrier@gmail.com', 'CS3S8L7Q!8', 'Andeee', 'Bourquin', '2015-06-09', 'Utilitatis causa amicitia est quaesita.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quid iudicant sensus? An eiusdem modi? Suo genere perveniant ad extremum; Quid sequatur, quid repugnet, vident. Duo Reges: constructio interrete. Quae sequuntur igitur? \n\n', '6644 Golden Lane', 'Cambridge', 'Q8J K4E', 'Prince Edward Island', 'Ukraine', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(923, '', '', 'aLatshaw@gmail.com', 'Z2MIS92E!8', 'Rani', 'Pullman', '2004-11-07', 'Tu quidem reddes;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quid me istud rogas? Hic ambiguo ludimur. Tuo vero id quidem, inquam, arbitratu. Duo Reges: constructio interrete. \n\n', '8453 Park Avenue', 'Vancouver', 'SO G5V', 'Arizona', 'Kuwait', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(924, '', '', 'rZobel@gmail.com', 'AVKJA4F2!8', 'Fredericka', 'Bourquin', '2003-08-05', 'Oculorum, inquit Plato, est in nobis sensus acerrimus, quibus sapientiam non cernimus.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Bonum liberi: misera orbitas. Quid iudicant sensus? Hoc simile tandem est? Duo Reges: constructio interrete. \n\n', '2045 Piermont Drive', 'Richmond', 'J8V M1A', 'New Mexico', 'Saint Vincent and the Grenadines', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(925, '', '', 'aKeesee@gmail.com', '6LS7OZW1!8', 'Marybelle', 'Milling', '2009-05-06', 'Non semper, inquam;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in rebus apertissimis nimium longi sumus. Duo Reges: constructio interrete. Nulla erit controversia. Praeclare hoc quidem. Et ille ridens: Video, inquit, quid agas; Haeret in salebra. \n\n', '8029 Waverton Street', 'Petersburg', 'Y1I L', 'Rhode Island', 'China', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(926, '', '', 'aBrandt@gmail.com', 'YE72WB3E!8', 'Nathalia', 'Rohloff', '2009-04-24', 'Sed haec omittamus;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quo tandem modo? Iam in altera philosophiae parte. Immo videri fortasse. Peccata paria. Nonne igitur tibi videntur, inquit, mala? Nam Pyrrho, Aristo, Erillus iam diu abiecti. \n\n', '4104 Emmet Road', 'Stafford', 'F1L X4U', 'Virginia', 'Saint Helena', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(927, '', '', 'eMercer@gmail.com', 'AIVI6I55!8', 'Louella', 'Winter', '2011-10-21', 'Quae cum dixisset, finem ille.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quare attende, quaeso. Eaedem res maneant alio modo. Prioris generis est docilitas, memoria; Refert tamen, quo modo. \n\n', '7399 Bramble Lane', 'Orlando', 'Z8W R0P', 'Maine', 'Kuwait', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(928, '', '', 'iOldman@gmail.com', 'LF8JI57G!8', 'Steffie', 'Dunham', '2003-05-22', 'Summum enÃ­m bonum exposuit vacuitatem doloris;\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Recte, inquit, intellegis. Ne discipulum abducam, times. Hoc tu nunc in illo probas. Ut optime, secundum naturam affectum esse possit. Quae cum essent dicta, discessimus. Duo Reges: constructio interrete. \n\n', '1393 Emmet Road', 'Cleveland', 'F9D A6L', 'Massachusetts', 'Ukraine', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(929, '', '', 'aTurner@gmail.com', 'RU1BPY4A!8', 'Lyssa', 'Dampier', '2003-12-23', 'Illum mallem levares, quo optimum atque humanissimum virum, Cn.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. At multis se probavit. Proclivi currit oratio. Dici enim nihil potest verius. Duo Reges: constructio interrete. \n\n', '4890 Tavistock Place', 'Adelaide', 'Q2V QM', 'Rhode Island', 'Togo', 0);
INSERT INTO `user` (`id`, `role`, `dept`, `username`, `password`, `fname`, `lname`, `date`, `desc`, `street`, `city`, `postal`, `province`, `country`, `isActive`) VALUES
(930, '', '', 'lFurlough@gmail.com', 'K1ENON1A!8', 'Malissia', 'Tindel', '2013-06-12', 'Quem si tenueris, non modo meum Ciceronem, sed etiam me ipsum abducas licebit.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. In schola desinis. Quo tandem modo? Tibi hoc incredibile, quod beatissimum. Audeo dicere, inquit. Quibusnam praeteritis? \n\n', '8902 Mulholland Drive', 'Youngstown', 'R5Y I7U', 'Michigan', 'Mauritania', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;